### ISSUE TITLE
Issue with Volvo FH16 750 Truck pack

### ISSUE THREAD

**Issue by StjerneIdioten** [StjerneIdioten/AdjustableMirrors#30]
[https://www.yesmods.com/fs19-mods/trucks/european-trucks/volvo-fh16-trucks-lmrm](url)

It seems that the truck registers its own vehicletype and my theory is that this happens after that adjustable mirrors has injected itself into the vehicle types. A possible solution could be to register AM in the postload method or something like that.

**Comment by fcucino** [comment]
Confirmed also with other mods, but not every mod.
For example, CoursePlay calls the register function twice, one immediately and then on loadMap().

**Comment by StjerneIdioten** [comment]
Fixed in [v1.0.1.0](https://github.com/StjerneIdioten/AdjustableMirrors/releases/tag/v1.0.1.0)
