### ISSUE TITLE
[BUG] Can't use machines on dedi

### ISSUE THREAD

**Issue by fcucino** [StjerneIdioten/AdjustableMirrors#33]
#20 
If you start a fresh savegame on a dedi server and you try to buy something, a LUA error will appear in the log and you can't enter the tractor.

![fsScreen_2019_06_27_16_32_28](https://user-images.githubusercontent.com/24813315/60274875-2e258400-98f9-11e9-8553-8c697ca8935a.png)

[log.txt](https://github.com/StjerneIdioten/AdjustableMirrors/files/3335225/log.txt)

When you try to enter the vehicle an error will appear
[logServer.txt](https://github.com/StjerneIdioten/AdjustableMirrors/files/3335235/logServer.txt)

**Comment by StjerneIdioten** [comment]
Bug was caused by a wrong implementation of a fix to a different issue. Which made the server go out of synch with clients and therefor caused issues. Commit https://github.com/StjerneIdioten/AdjustableMirrors/commit/0b4f0ac4236caded386cda0be5e63a9962c7366d reverts this "fix"
