### ISSUE TITLE
[BUG] Can't join a existing dedi savegame

### ISSUE THREAD

**Issue by fcucino** [StjerneIdioten/AdjustableMirrors#34]
#20 
If the savegame is already saved (this mod was never used before) you can't join dedi game because screen is freezed on sync page.

(Tested only on dedi)

[log.txt](https://github.com/StjerneIdioten/AdjustableMirrors/files/3335262/log.txt)
[logServer.txt](https://github.com/StjerneIdioten/AdjustableMirrors/files/3335269/logServer.txt)

**Comment by StjerneIdioten** [comment]
The fix for #33 fixes this as well.
